[package]
name = "das-pay"
description = "People's payment engine."
version = "0.1.0"
edition = "2021"
authors = ["doggo"]

[dependencies]
anyhow = "^1.0"
csv = "^1.1"
serde = { version = "^1.0", features = ["derive"] }

[dev-dependencies]
tempdir = "^0.3"
